# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QSpectrogramOptions.ui',
# licensing of 'QSpectrogramOptions.ui' applies.
#
# Created: Tue Feb  4 16:33:56 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SpectrogramOptions(object):
    def setupUi(self, SpectrogramOptions):
        SpectrogramOptions.setObjectName("SpectrogramOptions")
        SpectrogramOptions.resize(878, 283)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SpectrogramOptions)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(SpectrogramOptions)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cb_followSound = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_followSound.sizePolicy().hasHeightForWidth())
        self.cb_followSound.setSizePolicy(sizePolicy)
        self.cb_followSound.setObjectName("cb_followSound")
        self.gridLayout_7.addWidget(self.cb_followSound, 0, 0, 1, 3)
        self.cb_pcen = QtWidgets.QCheckBox(self.groupBox)
        self.cb_pcen.setObjectName("cb_pcen")
        self.gridLayout_7.addWidget(self.cb_pcen, 1, 0, 1, 1)
        self.cb_remove_noise = QtWidgets.QCheckBox(self.groupBox)
        self.cb_remove_noise.setObjectName("cb_remove_noise")
        self.gridLayout_7.addWidget(self.cb_remove_noise, 1, 3, 1, 1)
        self.cb_todb = QtWidgets.QCheckBox(self.groupBox)
        self.cb_todb.setObjectName("cb_todb")
        self.gridLayout_7.addWidget(self.cb_todb, 1, 4, 1, 1)
        self.cb_normalize = QtWidgets.QCheckBox(self.groupBox)
        self.cb_normalize.setObjectName("cb_normalize")
        self.gridLayout_7.addWidget(self.cb_normalize, 1, 5, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 2, 0, 1, 2)
        self.combo_fft = QtWidgets.QComboBox(self.groupBox)
        self.combo_fft.setObjectName("combo_fft")
        self.gridLayout_7.addWidget(self.combo_fft, 2, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 4, 1, 1)
        self.combo_window = QtWidgets.QComboBox(self.groupBox)
        self.combo_window.setObjectName("combo_window")
        self.gridLayout_7.addWidget(self.combo_window, 2, 5, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 3)
        self.combo_hop_length = QtWidgets.QComboBox(self.groupBox)
        self.combo_hop_length.setObjectName("combo_hop_length")
        self.gridLayout_7.addWidget(self.combo_hop_length, 3, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 3, 4, 1, 1)
        self.combo_scale = QtWidgets.QComboBox(self.groupBox)
        self.combo_scale.setObjectName("combo_scale")
        self.gridLayout_7.addWidget(self.combo_scale, 3, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 4, 0, 1, 3)
        self.combo_specType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_specType.sizePolicy().hasHeightForWidth())
        self.combo_specType.setSizePolicy(sizePolicy)
        self.combo_specType.setObjectName("combo_specType")
        self.combo_specType.addItem("")
        self.combo_specType.addItem("")
        self.gridLayout_7.addWidget(self.combo_specType, 4, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(SpectrogramOptions)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 0, 1, 2)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 2, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 0, 1, 2)
        self.spin_height = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_height.sizePolicy().hasHeightForWidth())
        self.spin_height.setSizePolicy(sizePolicy)
        self.spin_height.setObjectName("spin_height")
        self.gridLayout.addWidget(self.spin_height, 3, 2, 1, 1)
        self.slider_contrast = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_contrast.sizePolicy().hasHeightForWidth())
        self.slider_contrast.setSizePolicy(sizePolicy)
        self.slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.slider_contrast.setObjectName("slider_contrast")
        self.gridLayout.addWidget(self.slider_contrast, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 1, 0, 1, 1)
        self.spin_pix_in_sec = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_pix_in_sec.sizePolicy().hasHeightForWidth())
        self.spin_pix_in_sec.setSizePolicy(sizePolicy)
        self.spin_pix_in_sec.setObjectName("spin_pix_in_sec")
        self.gridLayout.addWidget(self.spin_pix_in_sec, 2, 2, 1, 1)
        self.cb_invert = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_invert.setObjectName("cb_invert")
        self.gridLayout.addWidget(self.cb_invert, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(378, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 3)
        self.combo_color_map = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_color_map.sizePolicy().hasHeightForWidth())
        self.combo_color_map.setSizePolicy(sizePolicy)
        self.combo_color_map.setObjectName("combo_color_map")
        self.gridLayout.addWidget(self.combo_color_map, 0, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(SpectrogramOptions)
        QtCore.QMetaObject.connectSlotsByName(SpectrogramOptions)

    def retranslateUi(self, SpectrogramOptions):
        SpectrogramOptions.setWindowTitle(QtWidgets.QApplication.translate("SpectrogramOptions", "Form", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("SpectrogramOptions", "Spectrogram", None, -1))
        self.cb_followSound.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "follow sound", None, -1))
        self.cb_pcen.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Use PCEN", None, -1))
        self.cb_remove_noise.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Remove noise", None, -1))
        self.cb_todb.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "To dB", None, -1))
        self.cb_normalize.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Normalize", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "n_fft", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Window type", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "hop length", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Scale", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "spectrogram type:", None, -1))
        self.combo_specType.setItemText(0, QtWidgets.QApplication.translate("SpectrogramOptions", "audible range", None, -1))
        self.combo_specType.setItemText(1, QtWidgets.QApplication.translate("SpectrogramOptions", "ultra sonic range", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("SpectrogramOptions", "Image", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Color map", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Number of pixels in a second", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Height", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Color contrast", None, -1))
        self.cb_invert.setText(QtWidgets.QApplication.translate("SpectrogramOptions", "Invert colors", None, -1))

